import { AppProps } from "next/app";
import Head from "next/head";
import React, { ReactNode } from "react";
import { FiSettings } from "react-icons/fi";
import { TooltipComponent } from "@syncfusion/ej2-react-popups";

type LayoutProps = {
	title?: string;
	children: ReactNode;
};

const Dashboard: React.FC<LayoutProps> = ({ children }) => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<div className="flex relative dark:bg-main-dark-bg">
					<div className="fixed right-4 bottom-4 z-[1000]">
						<TooltipComponent content="Setting" position="TopCenter">
							<button>
								<FiSettings />
							</button>
						</TooltipComponent>
					</div>
				</div>
			</div>
		</>
	);
};

export default Dashboard;
